package Customer;

import Booking.*;
import static Booking.BookingIoHandler.allBookings;
import Booking.BookingIoHandler.*;
import Customer.Customer;
import Customer.CustomerIoHandler;
import static Customer.CustomerIoHandler.allCustomers;
import Vehicle.Vehicle;
import Vehicle.VehicleIoHandler;
import static Vehicle.VehicleIoHandler.allVehicles;
import Admin.AdminDashboard;
import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import static java.lang.String.format;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/* @author Nikhil */
public class AddCustomerBooking extends javax.swing.JFrame {

    BookingIoHandler AIH ;
    CustomerIoHandler CIH ;
    VehicleIoHandler IIH ;
    public static String user ;

    public AddCustomerBooking(String user){
        allBookings.clear();
        allCustomers.clear();
        allVehicles.clear();
        AIH = new BookingIoHandler() ;
        CIH = new CustomerIoHandler();
        IIH = new VehicleIoHandler();
        initComponents();
        AddCustomerBooking.user = user;
        
    String [] time = {"07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00"};
    timeComboBox.setModel(new DefaultComboBoxModel(time));

    for (Vehicle list : allVehicles){
            vehicleComboBox.addItem(list.getID() + " | " + list.getManufacturer() + " " + list.getModel());
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        instructorLabel = new javax.swing.JLabel();
        crmLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        nameField1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        vehicleComboBox = new javax.swing.JComboBox<>();
        timeComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addAppointmentButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        appointmentDate = new com.toedter.calendar.JDateChooser();
        jSpinner1 = new javax.swing.JSpinner();
        nameField2 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        manufacturerField = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        modelField = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        mfgField = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        dRateField = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        colorField = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        totalField = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        vRegField = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(0, 153, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("STCaiyun", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Add  Booking");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 170, -1));

        exitLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });
        jPanel3.add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, 30));

        backLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });
        jPanel3.add(backLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel3.add(instructorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));
        jPanel3.add(crmLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel3.setText("Name");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 50, 30));

        nameField.setBackground(new java.awt.Color(0, 153, 51));
        nameField.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        nameField.setForeground(new java.awt.Color(204, 204, 204));
        nameField.setToolTipText("Password");
        nameField.setBorder(null);
        nameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFieldFocusGained(evt);
            }
        });
        jPanel3.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 190, 20));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 190, 10));

        nameField1.setBackground(new java.awt.Color(0, 51, 102));
        nameField1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        nameField1.setForeground(new java.awt.Color(204, 204, 204));
        nameField1.setToolTipText("Password");
        nameField1.setBorder(null);
        nameField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameField1FocusGained(evt);
            }
        });
        jPanel3.add(nameField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 129, 20));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 130, 10));

        vehicleComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vehicleComboBoxItemStateChanged(evt);
            }
        });
        jPanel3.add(vehicleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 160, -1));

        timeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        timeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeComboBoxActionPerformed(evt);
            }
        });
        jPanel3.add(timeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 90, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel7.setText("Days");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 70, 20));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel8.setText("Car Reg No.");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 90, 20));

        addAppointmentButton.setText("Add Booking");
        addAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAppointmentButtonActionPerformed(evt);
            }
        });
        jPanel3.add(addAppointmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, -1, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel9.setText("Pick up");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 70, 20));
        jPanel3.add(appointmentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 140, 30));

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jPanel3.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 140, -1));

        nameField2.setBackground(new java.awt.Color(0, 153, 51));
        nameField2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        nameField2.setForeground(new java.awt.Color(204, 204, 204));
        nameField2.setToolTipText("Password");
        nameField2.setBorder(null);
        nameField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameField2FocusGained(evt);
            }
        });
        jPanel3.add(nameField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 190, 20));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 190, 10));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Name");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 50, 30));

        manufacturerField.setBackground(new java.awt.Color(0, 153, 51));
        manufacturerField.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        manufacturerField.setForeground(new java.awt.Color(204, 204, 204));
        manufacturerField.setToolTipText("Password");
        manufacturerField.setBorder(null);
        manufacturerField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                manufacturerFieldFocusGained(evt);
            }
        });
        jPanel3.add(manufacturerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 190, 20));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 190, 10));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel5.setText("Manufacturer");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 100, 30));

        modelField.setBackground(new java.awt.Color(0, 153, 51));
        modelField.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        modelField.setForeground(new java.awt.Color(204, 204, 204));
        modelField.setToolTipText("Password");
        modelField.setBorder(null);
        modelField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                modelFieldFocusGained(evt);
            }
        });
        jPanel3.add(modelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 190, 20));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 190, 10));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel10.setText("Model");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 50, 30));

        mfgField.setBackground(new java.awt.Color(0, 153, 51));
        mfgField.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        mfgField.setForeground(new java.awt.Color(204, 204, 204));
        mfgField.setToolTipText("Password");
        mfgField.setBorder(null);
        mfgField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mfgFieldFocusGained(evt);
            }
        });
        jPanel3.add(mfgField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 190, 20));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 190, 10));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel11.setText("Mfg Year");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 70, 30));

        dRateField.setBackground(new java.awt.Color(0, 153, 51));
        dRateField.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        dRateField.setForeground(new java.awt.Color(204, 204, 204));
        dRateField.setToolTipText("Password");
        dRateField.setBorder(null);
        dRateField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dRateFieldFocusGained(evt);
            }
        });
        jPanel3.add(dRateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 190, 20));
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 190, 10));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel12.setText("Daily Rate(MYR)");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 130, 30));

        colorField.setBackground(new java.awt.Color(0, 153, 51));
        colorField.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        colorField.setForeground(new java.awt.Color(204, 204, 204));
        colorField.setToolTipText("Password");
        colorField.setBorder(null);
        colorField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                colorFieldFocusGained(evt);
            }
        });
        jPanel3.add(colorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 190, 20));
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 190, 10));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel13.setText("Color");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 70, 30));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel14.setText("TOTAL");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 90, 30));

        totalField.setBackground(new java.awt.Color(0, 153, 51));
        totalField.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        totalField.setForeground(new java.awt.Color(204, 204, 204));
        totalField.setToolTipText("Password");
        totalField.setBorder(null);
        totalField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                totalFieldFocusGained(evt);
            }
        });
        jPanel3.add(totalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 190, 20));
        jPanel3.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 190, 10));

        vRegField.setBackground(new java.awt.Color(0, 153, 51));
        vRegField.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        vRegField.setForeground(new java.awt.Color(204, 204, 204));
        vRegField.setToolTipText("Password");
        vRegField.setBorder(null);
        vRegField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vRegFieldFocusGained(evt);
            }
        });
        jPanel3.add(vRegField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 190, 20));
        jPanel3.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 190, 10));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel15.setText("Reg No.");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 130, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.requestFocusInWindow();
        EventQueue.invokeLater(() -> jPanel1.requestFocusInWindow());

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        dispose();
        BookingManagement AM = new BookingManagement();
        AM.show();

    }//GEN-LAST:event_backLabelMouseClicked

    private void nameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldFocusGained

    private void nameField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameField1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nameField1FocusGained

    
    private void addAppointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAppointmentButtonActionPerformed
    
        try {     
                boolean characterFound = false;
                Pattern namePattern = Pattern.compile("[^a-z ]", Pattern.CASE_INSENSITIVE);
                Matcher name = namePattern.matcher(nameField.getText());
                characterFound = name.find();
                SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
                String dateString;
                LocalDate DOA ; 
              
                if(characterFound == true || nameField.getText().length()<4){
                    JOptionPane.showMessageDialog(null,
                    "Incorrect Name format, Minimum 4 letters & no special characters or numbers allowed", "Warning",
                    JOptionPane.WARNING_MESSAGE);
                } else{
                    dateString = format.format(appointmentDate.getDate());
                    DOA = LocalDate.parse(dateString, formatter);
                    
                    if(DOA.isBefore(LocalDate.now())){
                        JOptionPane.showMessageDialog(null,
                        "Incorrect Date, Can't book an appointment for the past", "Warning",
                        JOptionPane.WARNING_MESSAGE);
                    }else{
                
        SimpleDateFormat dateForm = new SimpleDateFormat("dd-MM-YYYY");
        String date = dateForm.format(appointmentDate.getDate());
        String dateSlot = date + " " + timeComboBox.getSelectedItem().toString();
        SimpleDateFormat slotFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm");  
        Date slot = slotFormat.parse(dateSlot) ;
        
            if(BookingIoHandler.checkBooking(slotFormat.format(slot), vehicleComboBox.getSelectedItem().toString(), user) == null){

                int ID = 1 ;

                for (Booking list : allBookings) {
                    ID = allBookings.get(allBookings.size() - 1).getID() + 1;
                }
                
                int amount = Integer.parseInt(dRateField.getText()) * Integer.parseInt(jSpinner1.getValue().toString());
            
                Booking c = new Booking(ID, Integer.parseInt(jSpinner1.getValue().toString()), amount, nameField.getText(), user, vRegField.getText(),slot,'O');
                
                BookingIoHandler.allBookings.add(c);
                BookingIoHandler.addBooking();

                JOptionPane.showMessageDialog(null,
                        "Booking Successfully Added", "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                
                allCustomers.clear();
                allVehicles.clear();
                
                dispose();
                CustomerDashboard CM = new CustomerDashboard(user);
                CM.show();
            }
            else{
                JOptionPane.showMessageDialog(null,
                        "Booking Already Exists or Vehicle is booked, try a different vehicle or slot", "Error",
                        JOptionPane.WARNING_MESSAGE);
                
                    }
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(AddCustomerBooking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(AddCustomerBooking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null,
                                        "Please make sure all the fields are filled", "Error",
                                        JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_addAppointmentButtonActionPerformed

    private void timeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeComboBoxActionPerformed
       // System.out.println("Time: " + timeComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_timeComboBoxActionPerformed

    private void nameField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameField2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nameField2FocusGained

    private void manufacturerFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_manufacturerFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_manufacturerFieldFocusGained

    private void modelFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modelFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_modelFieldFocusGained

    private void mfgFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mfgFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_mfgFieldFocusGained

    private void dRateFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dRateFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dRateFieldFocusGained

    private void colorFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_colorFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_colorFieldFocusGained

    private void vehicleComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vehicleComboBoxItemStateChanged
        String manufacturer = null;
        String model = null ;
        String color = null;
        String vReg = null;
        int mfgYear = 0;
        int dRate = 0;
        
        
        String vehicle = vehicleComboBox.getSelectedItem().toString();
        char vehicleID = vehicle.charAt(0);
        int vID = Character.getNumericValue(vehicleID);
        
        for (Vehicle list : allVehicles) {
            if(list.getID() == vID){
               manufacturer = list.getManufacturer();
               model = list.getModel();
               color = list.getColor();
               mfgYear = list.getMfgYear();
               vReg = list.getvReg();
               dRate = list.getdRate();
               
            }
        }
       
        manufacturerField.setText(manufacturer);
        modelField.setText(model);
        colorField.setText(color);
        mfgField.setText(Integer.toString(mfgYear));
        vRegField.setText(vReg);
        dRateField.setText(Integer.toString(dRate));
        
        manufacturerField.setEditable(false);
        modelField.setEditable(false);
        colorField.setEditable(false);
        mfgField.setEditable(false);
        vRegField.setEditable(false);
        dRateField.setEditable(false);
        
        int total = dRate * Integer.parseInt(jSpinner1.getValue().toString());
        totalField.setText(Integer.toString(total));
        totalField.setEditable(false);
        
    }//GEN-LAST:event_vehicleComboBoxItemStateChanged

    private void totalFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totalFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_totalFieldFocusGained

    private void vRegFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vRegFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_vRegFieldFocusGained

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        String manufacturer = null;
        String model = null ;
        String color = null;
        String vReg = null;
        int mfgYear = 0;
        int dRate = 0;
        
        
        String vehicle = vehicleComboBox.getSelectedItem().toString();
        char vehicleID = vehicle.charAt(0);
        int vID = Character.getNumericValue(vehicleID);
        
        for (Vehicle list : allVehicles) {
            if(list.getID() == vID){
               manufacturer = list.getManufacturer();
               model = list.getModel();
               color = list.getColor();
               mfgYear = list.getMfgYear();
               vReg = list.getvReg();
               dRate = list.getdRate();
               
            }
        }
       
        manufacturerField.setText(manufacturer);
        modelField.setText(model);
        colorField.setText(color);
        mfgField.setText(Integer.toString(mfgYear));
        vRegField.setText(vReg);
        dRateField.setText(Integer.toString(dRate));
        
        manufacturerField.setEditable(false);
        modelField.setEditable(false);
        colorField.setEditable(false);
        mfgField.setEditable(false);
        vRegField.setEditable(false);
        dRateField.setEditable(false);
        
        int total = dRate * Integer.parseInt(jSpinner1.getValue().toString());
        totalField.setText(Integer.toString(total));
        totalField.setEditable(false);
    }//GEN-LAST:event_jSpinner1StateChanged
    
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomerBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomerBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomerBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomerBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCustomerBooking(user).setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAppointmentButton;
    private com.toedter.calendar.JDateChooser appointmentDate;
    private javax.swing.JLabel backLabel;
    private javax.swing.JTextField colorField;
    private javax.swing.JLabel crmLabel1;
    private javax.swing.JTextField dRateField;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel instructorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField manufacturerField;
    private javax.swing.JTextField mfgField;
    private javax.swing.JTextField modelField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nameField1;
    private javax.swing.JTextField nameField2;
    private javax.swing.JComboBox<String> timeComboBox;
    private javax.swing.JTextField totalField;
    private javax.swing.JTextField vRegField;
    private javax.swing.JComboBox<String> vehicleComboBox;
    // End of variables declaration//GEN-END:variables
}
